FROM jc21/rpmbuild-centos7:latest

LABEL maintainer="Jamie Curnow <jc@jc21.com>"

USER root

RUN yum -y update \
	&& curl -sSL https://get.haskellstack.org/ | sh \
	&& yum clean all \
	&& rm -rf /var/cache/yum \
	&& stack upgrade

USER rpmbuilder
